CREATE TABLE IF NOT EXISTS tasks
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    completed boolean NOT NULL,
    creation_date date NOT NULL,
    deleted boolean NOT NULL,
    target_date date,
    title character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT tasks_pkey PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS notifications
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone NOT NULL,
    message character varying(500) NOT NULL,
    read boolean NOT NULL,
    read_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    password character varying(255),
    username character varying(255),
    CONSTRAINT users_pkey PRIMARY KEY (id)
)