services:
  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: task5-prod
      SRPING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/app_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: '123456'
    networks:
      - app-network
    volumes:
      - app-data:/data

  postgres-db:
    image: postgres:16
    container_name: app-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: app_db
    ports:
      - '5434:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  app-data:
  postgres-data:

networks:
  app-network:
    driver: bridge